#! /bin/sh

# keyborad daemon
sxhkd &

# setting number of screens
bspc monitor -d 1 2 3 4 5 6 7

# bspwm configs for look and feel
bspc config border_width		2
bspc config border
bspc config window_gap          	12
bspc config top_padding			32
bspc config bottom_padding		0
bspc config left_padding		0
bspc config right_padding	    	0
bspc config split_ratio			0.50
bspc config borderless_monocle		true
bspc config gapless_monocle		true
bspc config click_to_focus		false
bspc config paddingless_moncle		true
bspc config focus_by_distance		true
bspc config focus_follows_pointer	true
bspc config pointer_modifer mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
#bspc config border_radius		10

# border color
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"


# desktop rules
bspc rule -a Chromium desktop='^2'
bspc rule -a Firefox desktop='^2'
bspc rule -a feh state=floating follow=on
bspc rule -a Spotify desktop='^4' 
bspc rule -a Telegram-desktop desktop='^5' 
bspc rule -a kitty desktop='^3'
bspc rule -a Code desktop='^1' follow=off state='tiled'
bspc rule -a Zathura state='tiled'
bspc rule -a flameshot state='floating'
bspc rule -a Pavucontrol state='floating' floow='on'


# auto starting daemon
xsetroot -cursor_name left_ptr &
nitrogen --restore &
$HOME/.config/polybar/launch.sh
picom -f &
flameshot &
lxsession &
#variety &
#pcmanfm -d &
